#region License Information (GPL v3)

/*
    ShareX - A program that allows you to take screenshots and share any file type
    Copyright (c) 2007-2026 ShareX Team

    This program is free software; you can redistribute it and/or
    modify it under the terms of the GNU General Public License
    as published by the Free Software Foundation; either version 2
    of the License, or (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program; if not, write to the Free Software
    Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.

    Optionally you can also view the license at <http://www.gnu.org/licenses/>.
*/

#endregion License Information (GPL v3)

// Ported from ShareX v21.0.0 (commit d2502561f63fc3ff502cacd91514e3f7f2948c74),
// file ShareX.HelpersLib/Extensions/NumberExtensions.cs (ToSizeString,
// ToDecimalString, suffix tables) and StringExtensions.cs (Repeat).
//
// Extracted into the indexer rather than pulling in HelpersLib, because these are
// the only helpers the indexer needs and the output format depends on their exact
// rounding and suffix behaviour.

using System.Globalization;

namespace ShareX.Tools.Indexing;

internal static class IndexerFormatting
{
    private static readonly string[] SuffixDecimal = { "B", "KB", "MB", "GB", "TB", "PB", "EB" };
    private static readonly string[] SuffixBinary = { "B", "KiB", "MiB", "GiB", "TiB", "PiB", "EiB" };

    /// <summary>
    /// Byte-size formatting, matching upstream exactly: values below one unit are
    /// printed as whole bytes, the divisor is 1000 or 1024 depending on
    /// <paramref name="binary"/>, and the mantissa uses a fixed number of decimal
    /// places (clamped to 0..3) rather than general rounding.
    /// </summary>
    public static string ToSizeString(this long size, bool binary = false, int decimalPlaces = 2)
    {
        int bytes = binary ? 1024 : 1000;

        if (size < bytes)
        {
            return Math.Max(size, 0) + " B";
        }

        int place = (int)Math.Floor(Math.Log(size, bytes));

        // Guard the suffix lookup: upstream indexes the table directly, which
        // would throw for an implausibly large value.
        place = Math.Clamp(place, 0, SuffixDecimal.Length - 1);

        double num = size / Math.Pow(bytes, place);
        string suffix = binary ? SuffixBinary[place] : SuffixDecimal[place];

        return num.ToDecimalString(Math.Clamp(decimalPlaces, 0, 3)) + " " + suffix;
    }

    public static string ToDecimalString(this double number, int decimalPlaces)
    {
        string format = "0";
        if (decimalPlaces > 0)
        {
            format += "." + new string('0', decimalPlaces);
        }

        // Invariant culture: the indexer's output is a document, and a
        // locale-dependent decimal separator would make it non-deterministic.
        return number.ToString(format, CultureInfo.InvariantCulture);
    }

    public static string Repeat(this string text, int count) =>
        count <= 0 || string.IsNullOrEmpty(text) ? "" : string.Concat(Enumerable.Repeat(text, count));

    /// <summary>
    /// Upstream's footer. The URL is upstream's own project link, kept because the
    /// footer is part of the generated document's format; it is not a UI element
    /// of this port.
    /// </summary>
    public static string GetFooter() =>
        "Generated by ShareX Directory Indexer on "
        + DateTime.UtcNow.ToString("yyyy-MM-dd 'at' HH:mm:ss 'UTC'", CultureInfo.InvariantCulture)
        + ". Latest version can be downloaded from: https://getsharex.com";
}
