#!/bin/bash
# Converts reference/ShareX/ShareX/ShareX_Icon.ico into packaging/ShareX-Mac.icns
# using only `sips` + `iconutil` (Command Line Tools; no Xcode / no asset
# catalogs available on this machine, see planning/adr/0002-build-toolchain.md).
#
# Verified recipe (2026-09-10, this repo):
#   sips -s format png ShareX_Icon.ico --out base.png
# yields a 256x256 RGBA PNG (the .ico's largest embedded image; verified with
# `file ShareX_Icon.ico` -> "4 icons, 256x256 with PNG image data ... 32
# bits/pixel"). 256x256 is the largest source pixels actually available, so
# the 512x512@2x (1024x1024 pixel) iconset slot is generated by upscaling
# that 256x256 base with `sips -z`, not from genuinely higher-resolution
# source art. Every other requested size is a downscale of the same base.
#
# Idempotent: always rebuilds packaging/ShareX-Mac.iconset and
# packaging/ShareX-Mac.icns from scratch; safe to re-run. Never writes into
# reference/ (read-only upstream tree).
set -euo pipefail

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$HERE/.." && pwd)"

ICO_SRC="${SXM_ICON_SRC:-$REPO_ROOT/reference/ShareX/ShareX/ShareX_Icon.ico}"
ICONSET="$HERE/ShareX-Mac.iconset"
ICNS_OUT="$HERE/ShareX-Mac.icns"
WORK="$(mktemp -d)"
trap 'rm -rf "$WORK"' EXIT

if [ ! -f "$ICO_SRC" ]; then
  echo "error: source icon not found at $ICO_SRC" >&2
  exit 1
fi

echo "==> extracting base PNG from $ICO_SRC"
sips -s format png "$ICO_SRC" --out "$WORK/base.png" >/dev/null

BASE_DIM="$(sips -g pixelWidth -g pixelHeight "$WORK/base.png" | awk '/pixelWidth/{w=$2} /pixelHeight/{h=$2} END{print w"x"h}')"
echo "==> base PNG is ${BASE_DIM}"

rm -rf "$ICONSET"
mkdir -p "$ICONSET"

# name size(px)
gen() {
  local name="$1" size="$2"
  sips -z "$size" "$size" "$WORK/base.png" --out "$ICONSET/$name" >/dev/null
}

gen icon_16x16.png       16
gen icon_16x16@2x.png    32
gen icon_32x32.png       32
gen icon_32x32@2x.png    64
gen icon_128x128.png     128
gen icon_128x128@2x.png  256
gen icon_256x256.png     256
# 256x256 source re-encoded at native size (no-op resize keeps the iconset
# entry present and correctly named).
gen icon_256x256@2x.png  512
gen icon_512x512.png     512
# Upscaled from the 256x256 source -- see header note above.
gen icon_512x512@2x.png  1024

echo "==> iconutil -c icns"
rm -f "$ICNS_OUT"
iconutil -c icns "$ICONSET" -o "$ICNS_OUT"

echo "==> built $ICNS_OUT"
file "$ICNS_OUT"
ls -la "$ICNS_OUT"
